---
- become: true
  hosts: master
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: 
        name: "{{ packages }}"
        state: present 
        update_cache: yes
      vars: 
        packages:
          - apt-transport-https
          - ca-certificates
          - curl 
          - software-properties-common
          - python3-pip
          - python3-setuptools

- import_playbook: install-docker.yml
- import_playbook: install-kubernetes.yml